name: Test
on:
  push:
    branches:
      - '**'
      
  workflow_dispatch:
    inputs:
      test_data:
        required: false
        type: string
        default: "test data"
      
      
jobs:
  print:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: print env
        env:
          ENV_VAR_NAME: "hello"
        run: echo $ENV_VAR_NAME
        
      - name: install azure cli
        if: ${{github.base_ref}}
        uses: elstudio/action-install-azure-cli@v1
        
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.2.0
        with:
          chrome-version: latest
        
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.0
      - name: build angular
        run: |
          ls /usr/bin/
          echo $CHROME_BIN
          
      - name: Frontend test result
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Jasmin report
          path: coverage/new-project/*html
